serverName: CS++
channelID: 1053499749443059814
morningEmoji: "☀️ "
badEmoji: "🤬"
easterEggs:
- string: "cheesed to meet you"
  emoji: "🧀"
- string: "good corning"
  emoji: "🌽"
- string: "mroning"
  emoji: "🤡"
- string: "programmer socks"
  emoji: "🤤"
- string: "guys being dudes"
  emoji: "👨‍❤️‍💋‍👨"
